/**
 * BaPCod  -  a generic Branch-And-Price Code
 * @file   bcBapcodVersion.h
 * @author Ruslan SADYKOV <ruslan.sadykov@inria.fr>,
 * @author Francois VANDERBECK <fv@atoptima.com> 
 *  
 *  All Rights Reserved, Inria. [LICENCE]
 * 
 *
 * This file is generated.
 *
 *             DO NOT EDIT THIS FILE
 *
 */
 
 #define BAPCOD_VERSION "0.82.5"
 #define BAPCOD_VERSION_DATE "24/09/2023"
